### ISSUE TITLE
Error parsing slightly more complex crons

### ISSUE THREAD

**Issue by manavo** [cronhub-app/crontab#2]
I know I should try and open a PR, but I'll at least report it for now 🙂 

I tried adding the cron `4-29/12,39-59/12  * * * *`, and got the output:

> Every 12,39-59 seconds, seconds 4 through 29 past the minute

Which doesn't look quiiiiite right. It should be:

> Every 12th minute from 4 through 29, and every 12th minute from 39 through 59.

**Comment by manavo** [comment]
I just looked and saw that you're using the [cronstrue library](https://github.com/bradymholt/cRonstrue), and the issue comes from there.

So I've opened an issue there: https://github.com/bradymholt/cRonstrue/issues/133

If it gets fixed there, hopefully it'll just be updating the dependency here.

**Comment by pg-randy** [comment]
Issue opened by manavo was closed as a duplicate, here is the open issue: https://github.com/bradymholt/cRonstrue/issues/124

**Comment by randallreedjr** [comment]
Issue opened by manavo was closed as a duplicate, here is the open issue: bradymholt/cRonstrue#124

**Comment by randallreedjr** [comment]
@manavo FYI, I just opened a PR on cRonstrue: https://github.com/bradymholt/cRonstrue/pull/163

**Comment by randallreedjr** [comment]
@tiggreen cRonstrue merged in my fix, I opened a PR to upgrade to the latest version
